nzxt-kraken3: Improve things noticed in #43, always return -ENODATA if device is faulty
liquidctl/liquidtux pull request #56
Opened 2023-10-10 18:12 UTC by aleksamagicka

This PR:
- improves the things @amezin commented on in #43
- adds a few comments to those parts
- formats the kraken3_raw_event() signature to be on one line
- improves the faultiness logic to always return -ENODATA if the device reports it's faulty. Otherwise, stale data would be returned
- notes the faultiness reporting in the docs

2023-10-10 20:13 UTC, amezin requested changes

2023-10-10 20:13 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Can't it simply be `mutex_lock_interruptible()`?

And after successful locking, check whether a request is needed, or if there's already a response that could be returned. And if the request is necessary - reinit completion, send the request, wait for completion. And another waitqueue shouldn't be necessary at all - unless I misunderstand something

2023-10-11 16:22 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
If we're in this function, the data is stale and the request is needed. The idea is to have only one reader request the sensor data per a refresh cycle - the rest, if they exist, wait until they are signaled.

`mutex_lock_interruptible()` would just make the readers wait one by one with the possibility of being interrupted, and the `else` branch wouldn't do anything (if only that were to change). If I understand your approach, it's a roundabout way to do the same - make readers check each after other if a request is needed - which the first one here already does for everyone and makes all others continue right off.

As for the completions, that was indeed one of my previous attempts at solving this - and Jonas noticed [an issue with reinitializing](https://github.com/liquidctl/liquidtux/pull/44#discussion_r1339156099) it. I reworked it to use a waitqueue, which does not need reinitializing, but is a bit more verbose with the flags.

2023-10-11 19:36 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
I'm suggesting that the entire body of the function should be holding the mutex. So `reinit_completion` and `wait_for_completion` would have no chance to happen concurrently - since both will be performed under the same lock. `else` branch for the lock would be just "return an error" (and the only possible error is "interrupted").

IMO it's much easier to re-check whether the last received report is outdated after the lock had been acquired - compared to an extra waitqueue. And also `_trylock` isn't really the way mutexes are designed to be used. If there's no blocking `_lock` call anywhere, it's just an atomic flag.

With the current code - `_trylock` and waitqueue - I'm just not sure whether it's correct at all.

2023-10-12 05:57 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
> So `reinit_completion` and `wait_for_completion` would have no chance to happen concurrently - since both will be performed under the same lock

I think reinit_completion isn't even needed in your approach, since there aren't multiple readers at once to synchronize between, just waiting for the raw event...

> And also `_trylock` isn't really the way mutexes are designed to be used. If there's no blocking `_lock` call anywhere, it's just an atomic flag.

Sorry, but I can't agree. This is an example of a "busy" wait, where the main thread/task/whatever it is in the kernel takes control of the main section and others wait for it to complete/do something else, and a mutex is a solution for that scenario.

> With the current code - _trylock and waitqueue - I'm just not sure whether it's correct at all.

AFAICS, it is. But I'll whip up your approach (probably tomorrow) as on a glance it does seem simpler, as the mutex would be doing the waitqueue part for us.

2023-10-12 08:22 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
> I think reinit_completion isn't even needed in your approach, since there aren't multiple readers at once to synchronize between, just waiting for the raw event...

Without reinit, any wait (except the 1st one) would "complete" immediately. I belive it's not what you need for Z53 - you actually need to wait (unless there's a up-to-date report already, that you can return immediately).

> Sorry, but I can't agree. This is an example of a "busy" wait, where the main thread/task/whatever it is in the kernel takes control of the main section and others wait for it to complete/do something else, and a mutex is a solution for that scenario.

But it's not a busy wait - you're using the waitqueue, not just spinning in a loop and checking some condition

2023-10-12 19:43 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
... although doing `complete_all()` everywhere could simplify things (no need to think whether it's X53 or Z53 - differences would end on the report parser code).

Also, balancing `_wait` and `_complete` always feels fragile to me. Will it still work correctly if userspace sent a request through hidraw?

2023-10-15 07:32 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Pushed the `mutex_lock_interruptible()` variant, please take a look.

> Also, balancing _wait and _complete always feels fragile to me. Will it still work correctly if userspace sent a request through hidraw?

The driver will pick up the returned sensor report in raw event, do a `complete()` and set `priv->updated`. When data becomes stale, the reading function for the Z53 could just pass through the wait because there's at least one pending `complete()` from before... A reinit before waiting could resolve that, but AFAICS there would be a race condition between it being reinit and `complete()`-d in raw event.

These seem like the only drivers in hwmon that are HID based (and enable hidraw):

![](https://i.gyazo.com/99f424650bc531aa160a5266752bbaef.png)

So I'm not sure if the driver should try to workaround unwanted status reports (maybe checking timestamps, trying reinit or something else) or if that falls into "you're on your own with hidraw for status reports with a driver loaded".

2023-10-15 07:45 UTC, jonasmalacofilho commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Some misbehavior might be acceptable when hidraw is used, although I'm not sure where the line should be drawn.

In any case, "you're on your own with hidraw for status reports with a driver loaded" is probably going a bit too far, especially because our own project (liquidctl) is quite likely to be involved in that scenario.

And while we strive to keep liquidctl from making unnecessary direct hidraw accesses when a hwmon driver is available, the user might be running an older version of liquidctl, or justifiably need to use our `--direct-access` flag... not to mention use cases/features not covered by either the kernel driver or liquidctl.

2023-10-15 08:00 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
> In any case, "you're on your own with hidraw for status reports with a driver loaded" is probably going a bit too far, especially because our own project (liquidctl) is quite likely to be involved in that scenario.

Yes, thought about that as well... The approach I outlined might've been too harsh.

Is there a problem with locking the reinit with a `spin_lock_irqsave()`? Right now I'm testing that and that seems like a way forward (disable the interrupts for a moment, so no `complete()` meddling).

2023-10-16 10:00 UTC, aleksamagicka commented
Pushed what I had in mind regarding the spinlocks, please have a look. The calls could be more specific AFAICS (raw event is a softirq, so `_bh` should suffice), but I went with `_irqsave` as a starting point.

2023-10-16 17:15 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Oh, and you could just remove `HID_CONNECT_HIDRAW` and thus get rid of any issues related to hidraw access... 

But I still woudn't trust the device to never send unexpected reports - during/because of suspend/resume, for example.

And if I was the user I wouldn't like that.

2023-10-16 18:07 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Thanks for the overview. It's late here, but the wq reminds me of my previous approach of escaping a reinit with completions. Will look in detail tomorrow or so, hopefully.

> Taking a spinlock, especially around complete(), doesn't look correct.

Most likely! What I wanted is to disable the softirq (raw event), but that (should) be just a design workaround fix, in essence.

> Oh, and you could just remove HID_CONNECT_HIDRAW and thus get rid of any issues related to hidraw access...

Thought about that, see my comments above. But that's the nuclear option and would screw with liquidctl, at the least. Hopefully this attempt works out and we collectively agree on a v1.

2023-10-18 17:22 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
> I believe there is a way to disable irq or softirq/bh (and _raw_event is softirq, if I recall correctly) without introducing an otherwise useless spinlock.

Looked at this some more, and found [this](https://linux-kernel-labs.github.io/refs/heads/master/labs/deferred_work.html#locking). Something about CPUs racing with the "manual" functions, seems safe to say that using spinlocks resolves that uncertainty. I also looked at some other drivers in the kernel, and they used `_bh` to quickly reset or capture some states, which is what should happen here with the completion.

I also acquired a Gigabyte Waterforce X240 today, which behaves like the Z53: a request must be sent to get the status report. The basic version of that driver is <500 lines of code right now and I intend to send it to the mailing list to gain feedback on the `_bh` solution, before venturing into waitqueues again here, as the problem at hand is pretty much the same.

2023-10-22 17:28 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
Welp, [looks like](https://lkml.org/lkml/2023/10/22/177) we won't get Guenter's opinion soon.

2023-10-22 19:50 UTC, amezin commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
When people write things like this, I don't understand whether they're serious, angry or joking.

Anyway, the approach with waitqueue+mutex is:

1) working correctly in nzxt-smart2
2) in the end it was accepted into the kernel

"completion" is internally a "waitqueue", so it's also the approach with minimal number of synchronization primitives.

Oh, and also treat all my words as suggestions: not blocking merging, not a block for submitting the patch upstream.

2023-10-22 20:08 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	if (mutex_trylock(&priv->z53_status_request_lock)) {
> When people write things like this, I don't understand whether they're serious, angry or joking.

I don't see any hwmon activity for like a month now, probably not joking? He made similar remarks before.

> Oh, and also treat all my words as suggestions: not blocking merging, not a block for submitting the patch upstream.

I'm not discounting your approach - in fact, that's the one that has the highest chance of getting accepted and is clear cut IMO. But as I've sent the Waterforce stuff already as a minimal "repro" of the completion approach (which might not be completely correct there, but we'll see), I'd like to see what he says, once he decides to review stuff again.

2023-12-05 19:59 UTC, aleksamagicka commented
This should now be rebased correctly. I've also incorporated lots of Guenter's feedback on the Waterforce driver here as well.

The faultiness handling irks me somewhat, I'll have to look into making it as resettable as possible.

2023-12-16 11:18 UTC, aleksamagicka commented
Fixed the faultiness logic so that it resets upon receiving a normal report and returns -ENODATA for a faulty cycle. I think the PR looks good as a whole (famous last words, though). Please review!

2023-12-19 05:28 UTC, amezin reviewed
To me it still looks like "one waitqueue for everything" would be simpler

2023-12-19 05:28 UTC, amezin commented on nzxt-kraken3.c
> +	spin_lock_bh(&priv->status_completion_lock);
Maybe I'm wrong - but as far as I understand it disables softirq only for the current cpu (core). And `raw_event` can still run concurrently on another cpu (it's softirq, right?).

2023-12-19 10:47 UTC, aleksamagicka commented on nzxt-kraken3.c
> +		if (!completion_done(&priv->fw_version_processed))
The docs still say `Calling complete_all() multiple times is a bug though.`.

2023-12-19 10:48 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	spin_lock_bh(&priv->status_completion_lock);
Good point. It is a softirq, yes.

That's a question for Guenter then, maybe he missed that for the Waterforce driver.

2024-01-10 18:35 UTC, aleksamagicka commented on nzxt-kraken3.c
> +	spin_lock_bh(&priv->status_completion_lock);
You were right regarding the concurrency, Guenter accepted a patch for the gigabyte_waterforce driver. Pushed the commit for this. (CI seems to fail on master, seemingly unrelated to my changes.)

2024-01-18 18:37 UTC, aleksamagicka commented
I'd like to merge this PR this month, if anyone has any comments please say. (The merge window is delayed right now so there's a bit more time.)

2024-01-18 18:56 UTC, jonasmalacofilho commented
Realistically, I won't be able to do an in-depth review of this any time soon. But I have looked it over. 

Overall, LGTM. But I have *not* checked the kernel concurrency primitives being used for corner cases I might have forgotten (or that are otherwise not obvious).

Just one question: how were you able to determinate that the HID raw event handler will run in soft IRQ?

2024-01-18 19:17 UTC, aleksamagicka commented
> Realistically, I won't be able to do an in-depth review of this any time soon. But I have looked it over.
> 
> Overall, LGTM (and, as far as I'm concerned, you can proceed and merge this as is). But I have _not_ checked the kernel concurrency primitives being used for corner cases I might have forgotten (or that are otherwise not obvious).

Thanks. The concurrency code is now very similar to what is in the Gigabyte driver. Guenter will complain if he sees something anyway.

> Just one question: how were you able to determinate that the HID raw event handler will run in soft IRQ?

Using ftrace, seems to be softirq:

```
# tracer: function
#
# entries-in-buffer/entries-written: 4/4   #P:32
#
#                                _-----=> irqs-off/BH-disabled
#                               / _----=> need-resched
#                              | / _---=> hardirq/softirq
#                              || / _--=> preempt-depth
#                              ||| / _-=> migrate-disable
#                              |||| /     delay
#           TASK-PID     CPU#  |||||  TIMESTAMP  FUNCTION
#              | |         |   |||||     |         |
          <idle>-0       [028] ..s2.    75.127663: aqc_raw_event <-hid_input_report
          <idle>-0       [028] ..s2.    75.143658: aqc_raw_event <-hid_input_report
          <idle>-0       [028] ..s2.    76.135680: aqc_raw_event <-hid_input_report
          <idle>-0       [028] ..s2.    76.143685: aqc_raw_event <-hid_input_report
```

And Guenter didn't say otherwise for one of the commits :)

2024-01-19 13:11 UTC, aleksamagicka commented
@jonasmalacofilho, what was the concensus regarding merging - do we just rebase or do a merge commit?

2024-01-19 13:33 UTC, jonasmalacofilho commented
Well, now that you mention in, I guess consensus has _not_ been _explicitly_ reached.

Initially it seemed like we had settled on:

> So let's disable all but normal merge commits, like you suggested.
> —_me, replying to amezin, https://github.com/liquidctl/liquidtux/issues/31#issuecomment-1376667065, 2023-01-10_

But afterwards rebase came back:

> Also, is anything wrong with "Rebase and merge" method? It keeps the original commit message
> —_amezin, https://github.com/liquidctl/liquidtux/pull/39#issuecomment-1399253107, 2023-01-21_

---

After the latter exchange I re-enabled "Rebase and merge", and we've been using it since without issues, _as far as I'm aware._

So think you can use it too, assuming you think that a linear history is generally and in this case preferable.
(I don't think it's necessary to ping amezin to re-hash this, but that's an option too).

2024-01-19 13:51 UTC, aleksamagicka commented
> So let's disable all but normal merge commits, like you suggested.

Yes, that part confused me initially.

I think that a rebase is OK here, thanks!

2024-01-19 13:52 UTC, merged