ci: Bump Ubuntu and kernel versions for CI builds
liquidctl/liquidtux pull request #57
Opened 2023-10-10 18:32 UTC by aleksamagicka

Just noticed that the kernel versions the CI uses are fairly old. Bump them up to current ones, including the Ubuntu version.

---

Shouldn't break anything, I hope? Or should I leave the 5.x ones in and only add these new ones?

2023-10-10 19:02 UTC, amezin commented
I think for kernel versions we should have at least:

- `master`
- oldest version that we support (I guess it's 5.10)

5.15 was just the latest stable version at the time the pipeline was added. Maybe it would make sense to track the latest stable release (for the case when `master` is broken, for example).

For Ubuntu versions - maybe just set them to `ubuntu-latest` everywhere and forget?

2023-10-10 19:50 UTC, amezin requested changes

2023-10-10 19:50 UTC, amezin commented on .github/workflows/build.yml
> -          - v5.10
If we still support 5.10 - please keep it here.

What's the "oldest supported version" of the kernel?

2023-10-10 19:50 UTC, amezin commented on .github/workflows/build.yml
> +    runs-on: ubuntu-22.04
Maybe just `ubuntu-latest`?

Also, some other workflow files have `ubuntu-20.04` in them too

2023-10-11 05:44 UTC, aleksamagicka commented on .github/workflows/build.yml
> +    runs-on: ubuntu-22.04
`ubuntu-latest` SGTM.

> Also, some other workflow files have `ubuntu-20.04` in them too

I only see `build.yml` using 20.04, which ones also have it?

2023-10-11 05:50 UTC, aleksamagicka commented on .github/workflows/build.yml
> -          - v5.10
Will re-add 5.10.

> What's the "oldest supported version" of the kernel?

Right now, it's [4.14](https://kernel.org/category/releases.html). Ubuntu 20.04 is on 5.4, with updates to 5.8. I don't see a point going below that, although CI is free here.

2023-10-11 06:52 UTC, amezin commented on .github/workflows/build.yml
> -          - v5.10
I meant oldest supported by liquidtux. Not sure if we ever discussed that. @jonasmalacofilho 

Personally I think anything older than "latest Ubuntu LTS" (which is now 22.04) is likely not necessary

2023-10-11 06:54 UTC, amezin commented on .github/workflows/build.yml
> +    runs-on: ubuntu-22.04
Oops, my bad. They have `ubuntu-22.04`. But if we're switching to `latest` here, it makes sense to switch everywhere at once.

2023-10-11 11:09 UTC, jonasmalacofilho commented on .github/workflows/build.yml
> -          - v5.10
> I meant oldest supported by liquidtux. Not sure if we ever discussed that. @jonasmalacofilho

I don't have an opinion on this.

But the kernel from the "latest Ubuntu LTS" makes sense, at least as a starting point. And things on hwmon and hid move fairly slowly.

2023-10-11 15:56 UTC, aleksamagicka commented on .github/workflows/build.yml
> -          - v5.10
I've now changed it to 6.2, as that's what's in the current version of 22.04. Should I add anything else?

2023-10-11 19:11 UTC, amezin approved these changes

2023-10-11 21:57 UTC, merged